ferreplus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    path("accounts/", include("accounts.urls")),
    # Local apps
    path("", include("pages.urls")),
    path("posts/", include("posts.urls")),
    path("adminpanel/", include("adminpanel.urls")),
    path("barter/", include("barter.urls")),
    path("turns/", include("turns.urls")),
    path("employee/", include("employeepanel.urls")),
    path("payments/", include("payments.urls")),
    path("metrics_analysis/", include("metrics_analysis.urls")),
    path("catalog/", include("catalogo.urls"))
]

if settings.DEBUG: #Solo proyecto en desarrollo, falta para producción
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    HomePageView,
    ClientHomeView,
    AdmiHomeView,
    EmployeeHomeView,
    GoBack,
    PasswordChangeSuccessView,
    EmailEditSuccessView,
    ShowContactInfo,
    show_contact_info
)


urlpatterns = [
    path("home", HomePageView.as_view(), name="home"),
    path("adminpanel/", AdmiHomeView.as_view(), name="admi_home"),
    path("employee/", EmployeeHomeView.as_view(), name="employee_home"),
    path(
        "password/change/successful",
        PasswordChangeSuccessView.as_view(),
        name="password_change_success",
    ),
    path(
        "profile-edit-success",
        EmailEditSuccessView.as_view(),
        name="profile_edit_success",
    ),
    path("", ClientHomeView.as_view(), name="client_home"),
    path("", GoBack.as_view(), name="go_back"),
    path("contact/", show_contact_info, name="contact"),
]

turns/urls.py
from django.urls import path
from .views import (ProposeTurnsView,
                    TurnsListView, 
                    AppointmentCreateView, 
                    AppointmentCreateSuccessView, 
                    AppointmentListView, 
                    EmployeeAppointmentListView,
                    RegisterBarterView,
                    EmployeeBarterCancelView,
                    ConfirmCommittedBarterView,
                    )

urlpatterns = [
    path('barter/<int:barter_id>/propose_turns/', ProposeTurnsView.as_view(), name='propose_turns'),
    path('appointment/<int:turn_proposal_id>/', AppointmentCreateView.as_view(), name='select-turn'),
    path('list/<int:barter_id>/', TurnsListView.as_view(), name='turns_list' ),
    path('', AppointmentCreateSuccessView.as_view(), name='appointment_success'),
    path('appointments/', AppointmentListView.as_view(), name='appointments_list'),
    path('employee_appointments/<int:employee_id>/', EmployeeAppointmentListView.as_view(), name='employee_appointments_list'),
    path('register_barter/<int:barter_id>/<int:employee_id>', RegisterBarterView.as_view(), name='register_barter'),
    path('cancel_barter/<int:barter_id>/<int:employee_id>/', EmployeeBarterCancelView.as_view(), name='employee_cancel_barter'),
    path('confirm_committed_barter/<int:barter_id>/<int:employee_id>', ConfirmCommittedBarterView.as_view(), name='confirm_committed_barter'),
]

turns/models.py
from django.db import models
from barter.models import Barter
from branches.models import Branch
from accounts.models import CustomUser

class TurnProposal(models.Model):
    barter = models.ForeignKey(Barter, on_delete=models.SET_NULL, null=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True)
    date = models.DateField()
    start_time = models.CharField(max_length=5, null=True)
    end_time = models.CharField(max_length=5, null=True)
    proposer = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    selected = models.BooleanField(default=False)

    def __str__(self) :
        return f"{self.branch}\n Día: {self.date}\n Entre las {self.start_time} y las {self.end_time}"

class Appointment(models.Model):
    barter = models.OneToOneField(Barter, on_delete=models.SET_NULL, null=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True)
    date = models.DateField()
    time = models.TimeField()

    def __str__(self) :
        return f"{self.branch}\n Día: {self.date}\n {self.time} horas."
    
class CancellationReport(models.Model):
    barter = models.ForeignKey(Barter, on_delete=models.CASCADE)
    reason = models.TextField()

    def __str__(self) :
        return f"{self.barter}"

turns/forms.py
from django import forms
from .models import Appointment, TurnProposal, Branch, CancellationReport, Barter
from datetime import date, timedelta

class TurnProposalForm(forms.ModelForm):
    tomorrow = (date.today() + timedelta(days=1)).strftime('%Y-%m-%d')
    date = forms.DateField(
        label="Fecha",
        widget=forms.DateInput(
            attrs={
                "placeholder": ("Fecha"),
                "type": "date",
                "min": tomorrow,
                }
            ),
        )
    TIME_CHOICES = ([(f"{h:02d}:00", f"{h:02d}:00") for h in range(9, 20)])
    start_time = forms.ChoiceField(
        label="Rango horario desde",
        choices=TIME_CHOICES,
        widget=forms.Select()
    )
    end_time = forms.ChoiceField(
        label="hasta",
        choices=TIME_CHOICES,
        widget=forms.Select()
    )

    class Meta:
        model = TurnProposal
        fields = ['branch', 'start_time', 'end_time', 'date']
        labels = {"branch": "Sucursal"}

    def __init__(self, *args, **kwargs):
        super(TurnProposalForm, self).__init__(*args, **kwargs)
        self.fields['branch'].queryset = Branch.active_objects.all()
        for field_name, field in self.fields.items():
            field.required = True

    def clean(self):
        cleaned_data = super().clean()
        branch = cleaned_data.get("branch")
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")
        if start_time and end_time and start_time >= end_time:
            raise forms.ValidationError("La hora de inicio debe ser anterior a la hora de finalización.")
        return cleaned_data

class SelectTurnForm(forms.Form):
    turn_proposal = forms.ModelChoiceField(queryset=TurnProposal.objects.none())

    def __init__(self, barter, *args, **kwargs):
        super(SelectTurnForm, self).__init__(*args, **kwargs)
        self.fields['turn_proposal'].queryset = TurnProposal.objects.filter(barter=barter)



class AppointmentForm(forms.ModelForm):
    time = forms.ChoiceField(
        label="Hora",
        choices=[],
        widget=forms.Select()
    )

    class Meta:
        model = Appointment
        fields = ['time']

    def __init__(self, *args, **kwargs):
        turn_proposal = kwargs.pop('turn_proposal')
        branch = kwargs.pop('branch') 
        barter = kwargs.pop('barter')
        date = kwargs.pop('date')

        super(AppointmentForm, self).__init__(*args, **kwargs)

        start_hour = int(turn_proposal.start_time[:2])
        end_hour = int(turn_proposal.end_time[:2])
        TIME_CHOICES_APPOINTMENT = [
            (f"{h:02d}:00", f"{h:02d}:00") 
            for h in range(start_hour, end_hour)
        ]
        self.fields['time'].choices = TIME_CHOICES_APPOINTMENT

        self.instance.branch = branch
        self.instance.barter = barter
        self.instance.date = date 

class CancelBarterForm(forms.ModelForm):
    class Meta:
        model = CancellationReport
        fields = ['reason']
        labels = {'reason':''}

    def __init__(self, barter, *args, **kwargs):
        super().__init__(*args, **kwargs)

turns/views.py
from django.views.generic.edit import FormView
from django.shortcuts import get_object_or_404, redirect, render
from django.forms import modelformset_factory
from django.urls import reverse_lazy
from .models import Barter, TurnProposal, Appointment
from accounts.models import EmployeeUser
from .forms import TurnProposalForm, AppointmentForm, CancelBarterForm
from accounts.mixins import ClientRequiredMixin, EmployeeRequiredMixin
from django.views.generic import TemplateView, CreateView, View, DeleteView
from django.db.models import Q
from django.views.decorators.http import require_POST

class ProposeTurnsView(ClientRequiredMixin, FormView):
    template_name = 'turns/propose_turns.html'

    def get_success_url(self) -> str:
        barter_id = self.kwargs['barter_id']
        return reverse_lazy('turns_list', kwargs={'barter_id': barter_id})
    
    def get_form_class(self):
        return modelformset_factory(TurnProposal, form=TurnProposalForm, extra=1)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['barter'] = get_object_or_404(Barter, id=self.kwargs['barter_id'])
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'queryset': TurnProposal.objects.none()})
        return kwargs

    def form_valid(self, formset):
        barter = get_object_or_404(Barter, id=self.kwargs['barter_id'])
        if (barter.state != 'parcial_accepted'):
            barter.change_state('parcial_accepted')
        instances = formset.save(commit=False)
        for instance in instances:
            instance.barter = barter
            instance.proposer = self.request.user
            instance.save()
        return super().form_valid(formset)
    
    def post(self, request, *args, **kwargs):
        selected_barter_id = request.POST.get('barter_id')
        if selected_barter_id:
            return redirect('propose_turns', barter_id=selected_barter_id)
        return super().post(request, *args, **kwargs)
    
class TurnsListView(ClientRequiredMixin, TemplateView):
    model = TurnProposal
    template_name = 'turns/turns_list.html'
    context_object_name = 'turns'

    def get_queryset(self):
        user = self.request.user
        barter_id = self.kwargs['barter_id']
        return self.filter_turn_proposals(user, barter_id)

    def filter_turn_proposals(self, user, barter_id):
        return TurnProposal.objects.filter(
            Q(barter__requesting_post__author=user) | Q(barter__requested_post__author=user),
            Q(barter__id=barter_id)
        )

    def post(self, request, *args, **kwargs):
        selected_turn_id = request.POST.get('selected_turn_id')
        if selected_turn_id:
            return self.handle_selected_turn(selected_turn_id)
        return super().post(request, *args, **kwargs)

    @require_POST
    def handle_selected_turn(self, selected_turn_id):
        return redirect('select-turn', turn_id=selected_turn_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        barter_id = self.kwargs['barter_id']
        turns = self.filter_turn_proposals(user, barter_id)
        barter = get_object_or_404(Barter, id=barter_id)
        context['proposer'] = barter.requested_post.author
        context['turns'] = turns
        context['barter_id'] = barter_id
        return context

class AppointmentCreateView(ClientRequiredMixin, FormView, CreateView):
    model = Appointment
    form_class = AppointmentForm
    template_name = 'turns/select-turn.html'
    success_url = reverse_lazy('appointment_success')

    def form_valid(self, form):
        barter = self.get_form_kwargs()['barter']
        form.instance.barter = barter
        barter.change_state('accepted')
        form.instance.date = self.get_form_kwargs()['date']
        branch = self.get_form_kwargs()['branch']
        form.instance.branch = branch
        barter.accept(branch)
        appointment = form.save(commit=False)
        appointment.save()
        TurnProposal.objects.filter(barter=barter).delete()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        turn_proposal = TurnProposal.objects.get(id=self.kwargs['turn_proposal_id'])
        kwargs['turn_proposal'] = turn_proposal
        kwargs['branch'] = turn_proposal.branch
        kwargs['barter'] = turn_proposal.barter
        kwargs['date'] = turn_proposal.date
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        turn_proposal = TurnProposal.objects.get(id=self.kwargs['turn_proposal_id'])
        context['turn_proposal'] = turn_proposal
        return context
    
class AppointmentCreateSuccessView(ClientRequiredMixin,TemplateView):
    template_name = 'temp_messages/appointment_created.html'

class AppointmentListView(ClientRequiredMixin,TemplateView):
    model = Appointment
    template_name = 'turns/appointments_list.html'
    context_object_name = 'appointments'

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        context['appointments'] = Appointment.objects.filter(
            Q(barter__requesting_post__author=user) | Q(barter__requested_post__author=user)
        ) 
        return context
    
class EmployeeAppointmentListView(EmployeeRequiredMixin,TemplateView):
    model = Appointment
    template_name = 'turns/employee_appointments_list.html'
    context_object_name = 'appointments'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        employee = EmployeeUser.objects.get(id=self.kwargs['employee_id'])
        employee_branch = employee.branch
        context['appointments'] = Appointment.objects.filter(branch=employee_branch, barter__state='accepted')
        return context
    
class RegisterBarterView(EmployeeRequiredMixin, View):
    model = Barter
    def post(self, request, *args, **kwargs):
        barter_id = kwargs.get('barter_id')
        barter = get_object_or_404(Barter, id=barter_id)
        employee_id = kwargs.get('employee_id')
        employee = get_object_or_404(EmployeeUser, id=employee_id)
        income = request.POST.get('income')
        barter.register(employee, income)
        Appointment.objects.filter(barter=barter).delete()
        return redirect('barter_finished', employee_id)
    
class ConfirmCommittedBarterView(EmployeeRequiredMixin, View):
    template_name = 'turns/confirm_committed_barter.html'

    def post(self, request, *args, **kwargs):
        barter_id = kwargs.get('barter_id')
        employee_id = kwargs.get('employee_id')
        barter = get_object_or_404(Barter, id=barter_id)
        employee = get_object_or_404(EmployeeUser, id=employee_id)
        return render(request, self.template_name, {
            'barter_id': barter_id,
            'employee_id': employee_id,
            'barter': barter,
            'employee': employee
        })
    
class EmployeeBarterCancelView(EmployeeRequiredMixin, FormView):
    model = Barter
    form_class = CancelBarterForm
    template_name = "barter/employee_cancel_barter.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['employee'] = self.get_employee_object()
        context['barter'] = self.get_barter_object()
        return context

    def get_success_url(self) -> str:
        return reverse_lazy('employee_appointments_list', kwargs={'employee_id':self.kwargs['employee_id']})

    def get_barter_object(self):
        return get_object_or_404(Barter, pk=self.kwargs['barter_id'])
    
    def get_employee_object(self):
        return get_object_or_404(EmployeeUser, pk=self.kwargs['employee_id'])

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['barter'] = self.get_barter_object()
        return kwargs

    def form_valid(self, form):
        report = form.save(commit=False)
        barter = self.get_barter_object()
        report.barter = barter
        employee = self.get_employee_object()
        barter.employee = employee
        report.save()
        barter.delete()
        Appointment.objects.filter(barter=barter).delete()
        return super().form_valid(form)

templates/turns/appointments_list.html
{% extends "_base_wildcard_bootstrap.html" %}
{% load static %}

{% block custom_styles %}
    <link rel="stylesheet" href="{% static 'styles/generics/generic_list.css' %}">
{% endblock custom_styles %}

{% block title %}Mis Turnos{% endblock title %}

{% block content %}
<div class="list-container">
    <h1>Mis Turnos</h1>
    {% for appointment in appointments %}
        <div class="list-group-item">
            <div class="item-header">
                <h5>Día {{ appointment.date }} a las {{ appointment.time }}</h5>
                <p>{{ appointment.branch }}</p>
                <p>{{ appointment.barter }}</p>
            </div>
        </div>
    {% endfor %}
    <p><a href="{% url 'home' %}" class="btn btn-light">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"/>
          </svg>
            Volver
    </a></p>
</div>
{% endblock content %}

templates/turns/confirm_committed_barter.html
{% extends "_base_wildcard_bootstrap.html" %}
{% load static %}

{% block title %}Registrar Trueque{% endblock title %}
{% block content %}
<div class="container">
    <h1>Registrar Trueque</h1>
    <h5>Ingresos generados en base al Trueque</h5>
    <div class="button-container">
        <div>
            <p><form method="post" action="{% url 'register_barter' barter_id employee_id %}" class="register-barter-form">
                {% csrf_token %}
                <input type="hidden" name="barter_id" value="{{ barter_id }}">
                <input type="hidden" name="employee_id" value="{{ employee_id }}">
                <div class="form-group">
                    <label for="income">Ingreso</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">$</span>
                        </div>
                        <input type="number" step="0.01" name="income" class="form-control" id="income" value="0" style="width: 150px;">
                    </div>
                </div>
                <button type="submit" class="btn btn-success register-barter-button">Registrar Trueque</button>
            </form></p>
        </div>
        <p><a href="{% url 'employee_appointments_list' employee_id %}" class="btn btn-danger">
                Cancelar
        </a></p>
    </div>
</div>
{% endblock %}

templates/turns/employee_appointments_list.html
{% extends "_base_wildcard_bootstrap.html" %}
{% load static %}

{% block custom_styles %}
    <link rel="stylesheet" href="{% static 'styles/generics/generic_list.css' %}">
{% endblock custom_styles %}

{% block title %}Próximos Turnos{% endblock title %}

{% block content %}
<div class="list-container">
    <h1>Próximos Trueques</h1>
    {% for appointment in appointments %}
        <div class="list-group-item">
            <div class="item-header">
                <h5>Día {{ appointment.date }} a las {{ appointment.time }}</h5>
                <p>{{ appointment.barter }}</p>
                {% if appointment.barter.state == 'accepted' %}
                <form method="post" action="{% url 'confirm_committed_barter' appointment.barter.id employee_id %}" class="register-barter-form" onsubmit="return confirmRegister();">
                    {% csrf_token %}
                    <input type="hidden" name="barter_id" value="{{ appointment.barter.id }}">
                    <input type="hidden" name="employee_id" value="{{ employee_id }}">
                    <button type="submit" class="btn btn-success register-barter-button">Registrar Trueque</button>
                </form>
                <form method="post" action="{% url 'employee_cancel_barter' appointment.barter.id employee_id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" >Cancelar</button>
                </form>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    <p><a href="{% url 'home' %}" class="btn btn-light">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"/>
          </svg>
            Volver
    </a></p>
</div>
{% endblock content %}

templates/turns/propose_turns.html
{% extends "_base_wildcard_bootstrap.html" %}
{% load static %}

{% block title %}Proponer Turnos{% endblock title %}

{% block content %}
<div class="propose-turns-container">
    <h1>Proponer Turnos</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Proponer Turno</button>
    </form>
    <p><a href="{% url 'my_barters' %}" class="btn btn-light">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"/>
          </svg>
            Volver
    </a></p>
</div>
{% endblock content %}

templates/turns/select-turn.html
{% extends "_base_wildcard_bootstrap.html" %}
{% load static %}

{% block title %}Seleccionar Turno{% endblock title %}

{% block content %}
<div class="select-turn-container">
    <h1>Seleccionar Turno</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            <label for="id_branch">Sucursal:</label>
            {{ turn_proposal.branch }}
        </div>
        <div class="form-group">
            <label for="id_date">Fecha:</label>
            {{ turn_proposal.date }}
        </div>
        <div class="form-group">
            <label for="id_time">Hora:</label>
            {{ form.time }}
        </div>
        <button type="submit" class="btn btn-primary">Confirmar</button>
    </form>
    <p><a href="{% url 'turns_list' turn_proposal.barter.id %}" class="btn btn-light">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"/>
          </svg>
            Volver
    </a></p>
</div>
{% endblock content %}

templates/turns/turns_list.html
{% extends "_base_wildcard_bootstrap.html" %}
{% load static %}

{% block custom_styles %}
    <link rel="stylesheet" href="{% static 'styles/generics/generic_list.css' %}">
{% endblock custom_styles %}

{% block title %}Turnos Propuestos{% endblock title %}

{% block content %}
<div class="list-container">
    <h1>Turnos Propuestos</h1>
    {% for turn in turns %}
        <div class="list-group-item">
            <div class="item-header">
                <p>{{ turn }}</p>
            </div>
            {% if request.user != turn.proposer %}
            <form method="post" action="{% url 'select-turn' turn.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary" name="selected_turn_id" value="{{ turn.id }}">Seleccionar Turno</button>
            </form>
            {% endif %}
            </div>
    {% endfor %}
    {% if request.user == proposer %}
        <p><a href="{% url 'propose_turns' barter_id %}" class="btn btn-primary">Agregar</a></p>
    {% endif %}
    <p><a href="{% url 'my_barters' %}" class="btn btn-light">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"/>
          </svg>
            Volver
    </a></p>
</div>
{% endblock content %}