ferreplus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    path("accounts/", include("accounts.urls")),
    # Local apps
    path("", include("pages.urls")),
    path("posts/", include("posts.urls")),
    path("adminpanel/", include("adminpanel.urls")),
    path("barter/", include("barter.urls")),
    path("turns/", include("turns.urls")),
    path("employee/", include("employeepanel.urls")),
    path("payments/", include("payments.urls")),
    path("metrics_analysis/", include("metrics_analysis.urls")),
    path("catalog/", include("catalogo.urls"))
]

if settings.DEBUG: #Solo proyecto en desarrollo, falta para producción
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    HomePageView,
    ClientHomeView,
    AdmiHomeView,
    EmployeeHomeView,
    GoBack,
    PasswordChangeSuccessView,
    EmailEditSuccessView,
    ShowContactInfo,
    show_contact_info
)


urlpatterns = [
    path("home", HomePageView.as_view(), name="home"),
    path("adminpanel/", AdmiHomeView.as_view(), name="admi_home"),
    path("employee/", EmployeeHomeView.as_view(), name="employee_home"),
    path(
        "password/change/successful",
        PasswordChangeSuccessView.as_view(),
        name="password_change_success",
    ),
    path(
        "profile-edit-success",
        EmailEditSuccessView.as_view(),
        name="profile_edit_success",
    ),
    path("", ClientHomeView.as_view(), name="client_home"),
    path("", GoBack.as_view(), name="go_back"),
    path("contact/", show_contact_info, name="contact"),
]

payments/urls.py
from django.urls import path
from .views import PackageSelectionView, PaymentSuccessView
app_name = 'payments'

urlpatterns = [
    path("<int:post_id>/package/", PackageSelectionView.as_view(), name="package-selection"),
    path("successful/purchase/", PaymentSuccessView.as_view(), name="success")

]

posts/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    MyPostListView,
    MyPostDetailView,
    DeleteQuestionView,
    DeleteAnswerView,
    PostSearchView,
    PackageListView, 
    UpdatePackageView
)


urlpatterns = [
    path("", PostListView.as_view(), name="post_list"),
    path("my_posts/", MyPostListView.as_view(), name="my_post_list"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("my_post/<int:pk>/", MyPostDetailView.as_view(), name="my_post_detail"),
    path("post/new/", PostCreateView.as_view(), name="post_new"),
    path("post/<int:pk>/edit/", PostUpdateView.as_view(), name="post_edit"),
    path("post/<int:pk>/delete/", PostDeleteView.as_view(), name="post_delete"),
    path("search/", PostSearchView.as_view(), name="post_search_results"),
    path('delete_question/<int:question_id>/', DeleteQuestionView.as_view(), name='delete_question'),
    path('delete_answer/<int:question_id>/', DeleteAnswerView.as_view(), name='delete_answer'),
    path('packages/', PackageListView.as_view(),name="package_list"),
    path('packages/update_package/<int:pk>/', UpdatePackageView.as_view(),name="update_package"),
]

posts/models.py
from django.db import models
from django.utils import timezone
from django.apps import apps
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.core.validators import MaxLengthValidator
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.conf import settings
from branches.models import Branch

User = get_user_model()

class Package(models.Model):
    PACKAGE_NONE = 'none'
    PACKAGE_BRONCE = 'bronce'
    PACKAGE_PLATA = 'plata'
    PACKAGE_ORO = 'oro'
    
    PACKAGE_CHOICES = [
        (PACKAGE_NONE, 'Ninguno'),
        (PACKAGE_BRONCE, 'Bronce'),
        (PACKAGE_PLATA, 'Plata'),
        (PACKAGE_ORO, 'Oro'),
    ]
    name = models.CharField(max_length=10, choices=PACKAGE_CHOICES, unique=True,default=PACKAGE_NONE)
    price = models.DecimalField(max_digits=6, decimal_places=2)  # Precio del paquete
    priority = models.IntegerField(default=5) #Para ordenamiento de publicaciones

    def __str__(self):
        return self.get_name_display()

def create_package_purchase(post, package):
        PackagePurchase.objects.create(
            post=post,
            package=package,
            price=package.price
    )

class Post(models.Model):
    POST_STATUS_AVAILABLE = 'available'
    POST_STATUS_RESERVED = 'reserved'
    POST_STATUS_COMPLETED = 'completed'
    POST_STATUS_PAUSED = "paused"
    POST_STATUS_DELETED = "deleted"
    POST_STATUS_CHOICES = (
        (POST_STATUS_AVAILABLE, 'Disponible'),
        (POST_STATUS_RESERVED, 'Reservado'),
        (POST_STATUS_COMPLETED, 'Finalizado'),
        (POST_STATUS_PAUSED, "Pausado"),
        (POST_STATUS_DELETED, "Eliminado")
    )

    HERRAMIENTAS = "tools" #En la BD su campo se denomina con el String 
    CONSTRUCCION = "construction"
    FERRETERIA_GRAL = "general_hardware_store"
    ELECTRICIDAD = "electrical"
    FONTANERIA = "plumbing"
    JARDIN = "gardens"
    CHOICES = [
        (HERRAMIENTAS, 'Herramientas'),
        (CONSTRUCCION, 'Construcción'),
        (FERRETERIA_GRAL, 'Ferretería general'),
        (ELECTRICIDAD, "Electricidad"),
        (FONTANERIA, 'Fontanería'),
        (JARDIN, 'Jardin'),
    ]
    
    title = models.CharField(max_length=50,verbose_name="Titulo")
    author = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name="Autor") 
    body = models.TextField(blank=True, null=True) 
    image = models.ImageField(upload_to="post_images") #Para una imagen sola
    category = models.CharField(max_length=22, choices=CHOICES,verbose_name="Categoría")
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL,null=True,verbose_name="Sucursal") #Sucursal
    original_branch_id = models.IntegerField(null=True) #ID sucursal original para cuando eliminamos una sucursal y la publi se ponga en pausado
    new = models.BooleanField(blank=True, null=True,)
    brand = models.CharField(max_length=30,blank=True, null=True,verbose_name="Marca") #marca
    status = models.CharField(max_length=20, choices=POST_STATUS_CHOICES, default=POST_STATUS_AVAILABLE,) 
    package = models.ForeignKey(Package, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Paquete")
    package_start_date = models.DateTimeField(null=True, blank=True)  # Fecha de inicio del paquete
    deletion_reason = models.TextField(null=True, blank=True, verbose_name="Razón de eliminación")
    
    def has_unanswered_questions(self):
        return self.questions.filter(Q(answer__isnull=True) | Q(answer='')).exists()
    
    def __str__(self):
        return self.title
    
    def complete_post(self):
        self.status = 'completed'
        self.save()

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"pk": self.pk})
    
    def reserve_post(self):
        Barter = apps.get_model('barter', 'Barter')
        
        self.status='reserved'
        self.save()
        
        # Cancelar todos los trueques donde esta publicación está involucrada y no están ya cancelados
        self.requesting_barters.filter(~Q(state=Barter.BARTER_STATE_CANCELLED)).update(state=Barter.BARTER_STATE_CANCELLED)
        self.requested_barters.filter(~Q(state=Barter.BARTER_STATE_CANCELLED)).update(state=Barter.BARTER_STATE_CANCELLED)
    
    def delete_post(self, reason=None):
        Barter = apps.get_model('barter', 'Barter')
        self.status = self.POST_STATUS_DELETED
        self.deletion_reason = reason
        self.save()
        Barter.objects.filter(Q(requesting_post=self) | Q(requested_post=self)).exclude(state=Barter.BARTER_STATE_CANCELLED).update(state=Barter.BARTER_STATE_CANCELLED)
    
    def free_post(self):
        self.status = 'available'
        self.save()
    
    def change_package(self, new_package):
        """
        Cambia el paquete asociado a la publicación y guarda la transacción en la tabla de PackagePurchase.
        """
        # Guardar la fecha de inicio del nuevo paquete
        self.package_start_date = timezone.now()
        # Registrar la transacción de compra
        create_package_purchase(self, new_package)
        # Actualizar el paquete
        self.package = new_package
        self.save() 
        # Enviar correo electrónico al propietario de la publicación
        self.send_package_change_email(new_package)
        
    def send_package_change_email(self, new_package):
        subject = 'Cambio de paquete en tu publicación'
        plain_message = render_to_string('emails/package_change.txt', {
            'post': self,
            'package': new_package,
            'user': self.author,
        })
        html_message = render_to_string('emails/package_change.html', {
            'post': self,
            'package': new_package,
            'user': self.author,
        })
        send_mail(
            subject,
            plain_message,
            settings.DEFAULT_FROM_EMAIL,  # Remitente
            [self.author.email],   # Destinatario
            html_message=html_message,
            fail_silently=False,
        )

class Question(models.Model): 
    post = models.ForeignKey(Post, related_name='questions', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(validators=[MaxLengthValidator(150)])
    created_at = models.DateTimeField(auto_now_add=True)
    #Como va a ser siempre el dueño de la publicación el que responda la pregunta no necesito hacer una clase nueva
    answer = models.TextField(validators=[MaxLengthValidator(150)],blank=True, null=True)
    
    def __str__(self):
        return f'Question by {self.user.username} on {self.post.title}'

class PackagePurchase(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,verbose_name="Publicación")
    package = models.ForeignKey(Package, on_delete=models.CASCADE,verbose_name="Paquete")
    purchase_date = models.DateTimeField(auto_now_add=True,verbose_name="Fecha")
    price = models.DecimalField(max_digits=6, decimal_places=2,verbose_name="Precio")

    def __str__(self):
        return f"{self.post.title} - {self.package.name} - {self.price}"

#Para cuando podamos cargar mas imagenes
class ImagePost(models.Model):#
    image = models.ImageField(upload_to='post_images')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images', max_length=4)#related_name es el nombre que tiene la otra entidad para llamarla
    #Falta la limitacion de 1 a 4 imágenes
    
    def __str__(self):
        return f"Imagen de {self.post.title}"

posts/forms.py
from django import forms
from .models import Post,ImagePost, Question, Package

class UpdatePackageForm(forms.ModelForm):
    class Meta:
        model = Package
        fields = ['price']
    
    def __init__(self, *args, **kwargs):
        self.post_instance = kwargs.get('instance')  # Almacena la instancia del post
        super(UpdatePackageForm, self).__init__(*args, **kwargs)
        self.fields["price"].label = "Precio"

    def clean(self):
        cleaned_data = super().clean()
        new_price = cleaned_data.get('price')
        package_instance = self.instance
        
        # Compara el nuevo paquete con el paquete actual del post
        if self.post_instance and new_price == self.post_instance.price:
            raise forms.ValidationError("No puedes elegir el mismo precio que ya está asignado.")
        
        # Mapa de restricciones para validar diferencias de precios entre paquetes
        price_restrictions = {
            'oro': {'min_price': Package.objects.get(name='plata').price},
            'plata': {'min_price': Package.objects.get(name='bronce').price, 'max_price': Package.objects.get(name='oro').price},
            'bronce': {'min_price': Package.objects.get(name='none').price, 'max_price': Package.objects.get(name='plata').price}, 
        }

        # Validar restricciones
        if package_instance.name in price_restrictions:  # Usa el nombre de la instancia del objeto para obtener el nombre del paquete
            # Validación de no igualdad y restricciones de mínimo y máximo
            if 'min_price' in price_restrictions[package_instance.name]:
                if new_price == price_restrictions[package_instance.name]['min_price']:
                    raise forms.ValidationError(f"El precio del paquete '{package_instance.get_name_display()}' no puede ser igual al del paquete anterior.")

                if new_price < price_restrictions[package_instance.name]['min_price']:
                    raise forms.ValidationError(f"El precio del paquete '{package_instance.get_name_display()}' debe ser mayor que el del paquete anterior.")

            if 'max_price' in price_restrictions[package_instance.name]:
                if new_price == price_restrictions[package_instance.name]['max_price']:
                    raise forms.ValidationError(f"El precio del paquete '{package_instance.get_name_display()}' no puede ser igual al del siguiente paquete.")

                if new_price > price_restrictions[package_instance.name]['max_price']:
                    raise forms.ValidationError(f"El precio del paquete '{package_instance.get_name_display()}' debe ser menor que el del siguiente paquete.")

        return cleaned_data


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ["title","body","image","category","branch","new","brand", ] #Campos que va a completar el usuario
        widgets = {
            "title" : forms.TextInput(
                attrs= {
                    "class" : "forms-control",
                    "placeholder" : "Ingrese nombre"
                }
            )
        }

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields["title"].label = "Nombre del producto"
        self.fields["body"].label = "Descripción del producto"
        self.fields["category"].label = "Categoría del producto"
        self.fields["new"].label = "Nuevo"
        self.fields["brand"].label = "Marca"
        self.fields["image"].label = "Imagen del producto"
        self.fields["branch"].label= "Sucursal de preferencia"
        self.fields["branch"].queryset = Branch.objects.filter(is_active=True)

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'maxlength': 150}),
            
        }
        help_texts = {
            'content': 'Máximo 150 caracteres.',
        }
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields["content"].label = ""

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['answer']
        widgets = {
            'answer': forms.Textarea(attrs={'maxlength': 150})
        }
        help_texts = {
            'answer': 'Máximo 150 caracteres.',
        }
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields["answer"].label = ""
from .models import Post,ImagePost
from branches.models import Branch

# class MultipleFileInput(forms.ClearableFileInput):
#    allow_multiple_selected = True

# class MultipleFileField(forms.FileField):
#    def __init__(self, *args, **kwargs):
#        kwargs.setdefault("widget", MultipleFileInput())
#        super().__init__(*args, **kwargs)

#    def clean(self, data, initial=None):
#        single_file_clean = super().clean
#        if isinstance(data, (list, tuple)):
#            result = [single_file_clean(d, initial) for d in data]
#        else:
#            result = [single_file_clean(data, initial)]
#        return result

# class FileFieldForm(forms.Form):
#    file_field = MultipleFileField()

# class ImageForm(forms.ModelForm):
#    class Meta:
#        model = ImagePost
#        fields = ['image',]
# widgets = {
#    'image': forms.FileInput(attrs={'multiple': True}) -->Falla con esto, por eso se usa MultipleFileField
# }

#    def form_valid(self, form):
#        files = form.cleaned_data["file_field"]
#        for f in files:
#            if form.cleaned_data:
#                    image = form.cleaned_data['image']
#                    instance = ImagePost(image=image, post=self.object)
#                    instance.save()
#        return super().form_valid(form)

#    def __init__(self,*args,**kwargs):
#        super().__init__(*args,**kwargs)
#        self.fields["image"].label = "Imagen "
#
#    def clean_image(self): #No chequea un choto
#        images = self.cleaned_data_data.get['image']
#        if len(images) < 1:
#            raise forms.ValidationError("Debes subir al menos una imagen.")
#        if len(images) > 4:
#            raise forms.ValidationError("Solo puedes subir un máximo de 4 imágenes.")
#        return images

# def clean_images(self):
#    images = self.cleaned_data.get('images')
#    if not images:
#        raise forms.ValidationError("Debe cargar al menos una imagen.")
#    return images

templates/posts/detail/general_post_detail.html
<!-- templates/general_post_detail.html -->
{% extends "_base_wildcard_bootstrap.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="generic-container">
        {% block warning_sign_post %}{% endblock warning_sign_post %}
        <div class="row">
            <div class="col-md-8">
                <h1 class="text-black text-center">{{ post.title }}</h1>
                <p><strong>Descripción:</strong></p>
                <p>{{ post.body }}</p>
                {% block additional_fields %}{% endblock additional_fields %}
                <p><strong>Sucursal de preferencia:</strong> {% if post.branch %} {{ post.branch }} {% else %} {% endif %}</p>
                <p><strong>Categoría:</strong> {{ post.get_category_display }}</p>
                <p><strong>Nuevo:</strong> {{ post.new|yesno:"Sí,No" }}</p>
                <p><strong>Marca:</strong> {% if post.brand %} {{ post.brand }} {% else %} {% endif %}</p>
            </div>
            <div class="col-md-4">
                <div class="shadow border border-dark rounded-lg p-3">
                    <img src="{{ post.image.url }}" alt="Imagen de la publicación" class="img-thumbnail">
                </div>
            </div>
        </div>
        {% block questions %} {# Se deja este general para el cliente visitante de la publicación (los otros deben redefinir el bloque)#}
            <div class="mt-4">
                <div class="Questions">
                    <hr>
                    <h4> Preguntas: </h4>
                    {% block for-questions %}
                    {% for question in post.questions.all %}
                    <div class="border p-3 mb-3 rounded bg-light">
                        <p>{{ question.content }}</p>
                        {% block answer %}{% endblock answer %}
                        {% if question.answer %}
                            <div class="bg-secondary text-white p-3 rounded mt-2">
                                <p><strong>Respuesta:</strong> {{ question.answer }}</p>
                            </div>
                        {% endif %}
                        {% if user == question.user %}
                            <form method="post" action="{% url 'delete_question' question.id %}" onsubmit="return confirmDelete();">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Eliminar Pregunta</button>
                            </form>
                        {% endif %}
                    </div>
                    {% endfor %}
                    {% endblock for-questions %}
                    <hr>
                </div>
            </div>
        {% endblock questions %}
        {% block ask_question %}{% endblock ask_question %}
        {% block additional_content %}
            <script src="{% static '/styles/products/toggleResponseForm.js' %}"></script>
        {% endblock additional_content %}
        <div class="mt-4">
            <div class="buttons">
                {% block additional_buttons %}{% endblock additional_buttons %}
            </div>
        </div>
    </div>
</div>

{% endblock content %} 

templates/posts/detail/my_post_detail.html
<!-- templates/my_post_detail.html -->
{% extends "posts/detail/general_post_detail.html" %}
{% load static %}

{% block warning_sign_post %}
    {% if post.status == 'deleted' %}
        {% if post.deletion_reason %}
            <div class="alert alert-danger mt-3">
                <p class="font-weight-bold">¡Atención!</p>
                <p>Esta publicación ha sido eliminada por el empleado por el siguiente motivo: <strong>{{ post.deletion_reason }}</strong></p>
            </div>
        {% else %}
        <div class="alert alert-danger mt-3">
            <p class="font-weight-bold">¡Atención!</p>
            <p>Publicación <strong>ELIMINADA</strong></p>
        </div>
        {% endif %}
    {% else %}
        {% if post.status == 'paused' %}
        <div class="alert alert-danger mt-3">
            <p class="font-weight-bold">¡Atención!</p>
            <p>La publicación se encuentra en <strong>estado PAUSADO</strong> (no es visible a los demás usuarios) debido a que se eliminó la sucursal a la que correspondía. Para solucionar esto, edite la publicación y seleccione una sucursal disponible.</p>
        </div>
        {% endif %}
        {% if post.has_unanswered_questions %}
        <div class="alert alert-warning mt-3">
            <p class="font-weight-bold">¡Atención!</p>
            <p>Esta publicación tiene preguntas sin responder. Por favor, revisa y responde las preguntas pendientes.</p>
        </div>
        {% endif %}
    {% endif %}
{% endblock warning_sign_post %}

{% block additional_fields %}
    <p><strong>Paquete actual:</strong> {{ post.package }}</p> 
    {% if post.status != 'deleted' %}
        {% if post.package.name == 'none' %}
            <p><a href="{% url 'payments:package-selection' post.pk %}" class="btn btn-info">Aumentar visibilidad</a></p>
        {% else %}
            <p><a href="{% url 'payments:package-selection' post.pk %}" class="btn btn-info">Cambiar paquete</a></p>
        {% endif %}
    {% endif %}
{% endblock additional_fields %}

{% block for-questions %}
    {% for question, answer_form in questions_with_forms %}
    <div class="border p-3 mb-3 rounded bg-light">
        <p>{{ question.content }}</p>
        {% block answer %}
            {% if not question.answer %}
                {% if post.status != 'deleted' %}
                    <button class="btn btn-primary toggle-response-form" data-question-id="{{ question.id }}">Responder</button>
                {% endif %}
            {% else %}
                <div class="bg-secondary text-white p-3 rounded mt-2">
                    <p><strong>Respuesta:</strong> {{ question.answer }}</p>
                </div>
                {% if request.user == post.author and post.status != 'deleted'%}
                    <form method="post" action="{% url 'delete_answer' question.id %}" onsubmit="return confirmDeleteAnswer();">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Eliminar Respuesta</button>
                    </form>
                {% endif %}
            {% endif %}
            <div id="response-form-{{ question.id }}" class="response-form" style="display: none;">
                <form method="post" action="{% url 'my_post_detail' post.pk %}">
                    {% csrf_token %}
                    {{ answer_form.as_p }}
                    <button type="submit" class="btn btn-success mt-2">Enviar respuesta</button>
                </form>
            </div>
        {% endblock answer %}
    </div>
    {% endfor %}
{% endblock for-questions %}

{% block additional_buttons %}
    {% if post.status != 'deleted' %}
        <p><a href="{% url 'post_edit' post.pk %}"class="btn btn-warning">Editar publicación</a></p>
        <p><a href="{% url 'post_delete' post.pk %}" class="btn btn-danger" id="delete-post-button" data-post-status="{{ post.status }}">Eliminar publicación</a></p>
        <p><a href="{% url 'post_list' %}" class="btn btn-primary">Todas las publicaciones</a></p>
    {% endif %}
    <p><a href="{% url 'my_post_list' %}" class="btn btn-light">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"/>
        </svg>
            Volver
    </a></p>
{% endblock additional_buttons %}

templates/posts/detail/post_detail.html
<!-- templates/post_detail.html -->
{% extends "posts/detail/general_post_detail.html" %}

{% block additional_fields %}
    <p><strong>Autor:</strong> 
        <a href="{% url 'user_detail' post.author.id %}">
            <button style="border: solid; border-width: 1px;" class="menu-button">
            {{post.author }}
            </button>
        </a>
    </p>
{% endblock additional_fields %}

{% block ask_question %}
    <div class="mt-4">
        <h4>Realizar una pregunta</h4>
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <p><button class="btn btn-warning mt-2" type="submit">Preguntar</button></p>
        </form>
        <p><a href="{% url 'barter_request' post.pk%}" class="btn btn-success">Solicitar Trueque</a></p>
        <p><a href="{% url 'post_list' %}" class="btn btn-primary">Todas las publicaciones</a></p>
        <p><a href="{% url 'post_list' %}" class="btn btn-light">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"/>
            </svg>
                Volver
        </a></p>
    </div>
{% endblock ask_question %}

templates/posts/detail/post_detail_employee.html
<!-- templates/post_detail_employee.html -->
{% extends "posts/detail/general_post_detail.html" %}
{% load static %}

{% block additional_fields %}
    {% if post.author %}
        <p><strong>Autor:</strong> 
            <a href="{% url 'user_detail' post.author.id %}">
                <button style="border: solid; border-width: 1px;" class="menu-button">
                {{post.author }}
                </button>
            </a>
        </p>
    {% else %}
        <span>Autor no disponible</span>
    {% endif %}
{% endblock additional_fields %}

{% block for-questions %}
    {% for question in post.questions.all %}
    <div class="border p-3 mb-3 rounded bg-light">
        <p>{{ question.content }}</p>
        <form method="post" action="{% url 'delete_question_employee' post.pk question.id %}" onsubmit="return confirmDelete();">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Dar de baja pregunta</button>
        </form>
        {% if question.answer %}
            <div class="bg-secondary text-white p-3 rounded mt-2">
                <p><strong>Respuesta:</strong> {{ question.answer }}</p>
                <form method="post" action="{% url 'delete_answer_employee' post.pk question.id %}" onsubmit="return confirmDeleteAnswer();">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Dar de baja respuesta</button>
                </form>
            </div>
        {% endif %}
    </div>
    {% endfor %}
{% endblock for-questions %}


{% block additional_buttons %}
    <p>
        <a href="{% url 'post_delete_employee' post.pk %}" class="btn btn-danger">Dar de baja la publicación</a>
    </p>
    <p><a href="{% url 'post_list_employee' %}" class="btn btn-light">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"/>
        </svg>
            Volver
    </a></p>
{% endblock additional_buttons %}