barter/urls.py
from django.urls import path
from .views import (BarterCreateView, 
                    BarterCreateSuccessView, 
                    BarterListView, 
                    BarterCancelView, 
                    CommittedBartersListView,
                    BarterFinishedView,)

urlpatterns = [
    path('barter/create/<int:post_id>/', BarterCreateView.as_view(), name='barter_request'),
    path('barter/success/', BarterCreateSuccessView.as_view(), name='barter_success'),
    path('', BarterListView.as_view(), name='my_barters'),
    path('cancel/<int:pk>/', BarterCancelView.as_view(), name='barter_cancel'),
    path('committed/<int:employee_id>/', CommittedBartersListView.as_view(), name='committed_barters_list'),
    path('barter/finished/<int:employee_id>', BarterFinishedView.as_view(), name='barter_finished'),
]

ferreplus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    path("accounts/", include("accounts.urls")),
    # Local apps
    path("", include("pages.urls")),
    path("posts/", include("posts.urls")),
    path("adminpanel/", include("adminpanel.urls")),
    path("barter/", include("barter.urls")),
    path("turns/", include("turns.urls")),
    path("employee/", include("employeepanel.urls")),
    path("payments/", include("payments.urls")),
    path("metrics_analysis/", include("metrics_analysis.urls")),
    path("catalog/", include("catalogo.urls"))
]

if settings.DEBUG: #Solo proyecto en desarrollo, falta para producción
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    HomePageView,
    ClientHomeView,
    AdmiHomeView,
    EmployeeHomeView,
    GoBack,
    PasswordChangeSuccessView,
    EmailEditSuccessView,
    ShowContactInfo,
    show_contact_info
)


urlpatterns = [
    path("home", HomePageView.as_view(), name="home"),
    path("adminpanel/", AdmiHomeView.as_view(), name="admi_home"),
    path("employee/", EmployeeHomeView.as_view(), name="employee_home"),
    path(
        "password/change/successful",
        PasswordChangeSuccessView.as_view(),
        name="password_change_success",
    ),
    path(
        "profile-edit-success",
        EmailEditSuccessView.as_view(),
        name="profile_edit_success",
    ),
    path("", ClientHomeView.as_view(), name="client_home"),
    path("", GoBack.as_view(), name="go_back"),
    path("contact/", show_contact_info, name="contact"),
]

barter/models.py
from django.db import models
from posts.models import Post
from branches.models import Branch
from accounts.models import EmployeeUser
import datetime

class Barter(models.Model):
    BARTER_STATE_REQUESTED = 'requested'
    BARTER_STATE_ACCEPTED = 'accepted'
    BARTER_STATE_PARCIAL_ACCEPTED = 'parcial_accepted'
    BARTER_STATE_COMMITTED = 'committed'
    BARTER_STATE_CANCELLED = 'cancelled'
    BARTER_STATE_CHOICES = (
        (BARTER_STATE_REQUESTED, 'Solicitado'),
        (BARTER_STATE_ACCEPTED, 'Aceptado'),
        (BARTER_STATE_COMMITTED, 'Finalizado'),
        (BARTER_STATE_CANCELLED, 'Cancelado'),
        (BARTER_STATE_PARCIAL_ACCEPTED, 'Parcialmente Aceptado'),
    )
    requesting_post = models.ForeignKey(Post, related_name='requesting_barters', on_delete=models.SET_NULL, null=True)
    requested_post = models.ForeignKey(Post, related_name='requested_barters', on_delete=models.SET_NULL, null=True)
    branch = models.ForeignKey(Branch, related_name='barter_branch', on_delete=models.SET_NULL, null=True)
    state = models.CharField(max_length=20, choices=BARTER_STATE_CHOICES, default=BARTER_STATE_REQUESTED,) 
    employee = models.ForeignKey(EmployeeUser, related_name='barter_employee', on_delete=models.SET_NULL, null=True)
    income = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    finished_date = models.DateField(auto_now=False, null=True)  

    def delete(self):
        self.state = self.BARTER_STATE_CANCELLED
        self.requested_post.free_post()
        self.requesting_post.free_post()
        self.save()

    def change_state(self, state):
        self.state = state
        self.save()

    def accept(self, branch):
        self.state = 'accepted'
        self.branch = branch
        self.requested_post.reserve_post()
        self.requesting_post.reserve_post()
        self.save()

    def register(self, employee, income=0):
        self.change_state('committed')
        self.employee = employee
        self.income = income
        self.requested_post.complete_post()
        self.requesting_post.complete_post()
        # Registra la fecha en que el trueque fue registrado como finalizado por el empleado
        self.finished_date = datetime.date.today()  
        self.save()

    def get_cancellation_report(self):
        from turns.models import CancellationReport
        try:
            return self.cancellationreport_set.get()
        except CancellationReport.DoesNotExist:
            return None 

    def __str__(self) -> str:
        return self.requested_post.title +" x "+ self.requesting_post.title

posts/models.py
from django.db import models
from django.utils import timezone
from django.apps import apps
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.core.validators import MaxLengthValidator
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.conf import settings
from branches.models import Branch

User = get_user_model()

class Package(models.Model):
    PACKAGE_NONE = 'none'
    PACKAGE_BRONCE = 'bronce'
    PACKAGE_PLATA = 'plata'
    PACKAGE_ORO = 'oro'
    
    PACKAGE_CHOICES = [
        (PACKAGE_NONE, 'Ninguno'),
        (PACKAGE_BRONCE, 'Bronce'),
        (PACKAGE_PLATA, 'Plata'),
        (PACKAGE_ORO, 'Oro'),
    ]
    name = models.CharField(max_length=10, choices=PACKAGE_CHOICES, unique=True,default=PACKAGE_NONE)
    price = models.DecimalField(max_digits=6, decimal_places=2)  # Precio del paquete
    priority = models.IntegerField(default=5) #Para ordenamiento de publicaciones

    def __str__(self):
        return self.get_name_display()

def create_package_purchase(post, package):
        PackagePurchase.objects.create(
            post=post,
            package=package,
            price=package.price
    )

class Post(models.Model):
    POST_STATUS_AVAILABLE = 'available'
    POST_STATUS_RESERVED = 'reserved'
    POST_STATUS_COMPLETED = 'completed'
    POST_STATUS_PAUSED = "paused"
    POST_STATUS_DELETED = "deleted"
    POST_STATUS_CHOICES = (
        (POST_STATUS_AVAILABLE, 'Disponible'),
        (POST_STATUS_RESERVED, 'Reservado'),
        (POST_STATUS_COMPLETED, 'Finalizado'),
        (POST_STATUS_PAUSED, "Pausado"),
        (POST_STATUS_DELETED, "Eliminado")
    )

    HERRAMIENTAS = "tools" #En la BD su campo se denomina con el String 
    CONSTRUCCION = "construction"
    FERRETERIA_GRAL = "general_hardware_store"
    ELECTRICIDAD = "electrical"
    FONTANERIA = "plumbing"
    JARDIN = "gardens"
    CHOICES = [
        (HERRAMIENTAS, 'Herramientas'),
        (CONSTRUCCION, 'Construcción'),
        (FERRETERIA_GRAL, 'Ferretería general'),
        (ELECTRICIDAD, "Electricidad"),
        (FONTANERIA, 'Fontanería'),
        (JARDIN, 'Jardin'),
    ]
    
    title = models.CharField(max_length=50,verbose_name="Titulo")
    author = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name="Autor") 
    body = models.TextField(blank=True, null=True) 
    image = models.ImageField(upload_to="post_images") #Para una imagen sola
    category = models.CharField(max_length=22, choices=CHOICES,verbose_name="Categoría")
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL,null=True,verbose_name="Sucursal") #Sucursal
    original_branch_id = models.IntegerField(null=True) #ID sucursal original para cuando eliminamos una sucursal y la publi se ponga en pausado
    new = models.BooleanField(blank=True, null=True,)
    brand = models.CharField(max_length=30,blank=True, null=True,verbose_name="Marca") #marca
    status = models.CharField(max_length=20, choices=POST_STATUS_CHOICES, default=POST_STATUS_AVAILABLE,) 
    package = models.ForeignKey(Package, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Paquete")
    package_start_date = models.DateTimeField(null=True, blank=True)  # Fecha de inicio del paquete
    deletion_reason = models.TextField(null=True, blank=True, verbose_name="Razón de eliminación")
    
    def has_unanswered_questions(self):
        return self.questions.filter(Q(answer__isnull=True) | Q(answer='')).exists()
    
    def __str__(self):
        return self.title
    
    def complete_post(self):
        self.status = 'completed'
        self.save()

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"pk": self.pk})
    
    def reserve_post(self):
        Barter = apps.get_model('barter', 'Barter')
        
        self.status='reserved'
        self.save()
        
        # Cancelar todos los trueques donde esta publicación está involucrada y no están ya cancelados
        self.requesting_barters.filter(~Q(state=Barter.BARTER_STATE_CANCELLED)).update(state=Barter.BARTER_STATE_CANCELLED)
        self.requested_barters.filter(~Q(state=Barter.BARTER_STATE_CANCELLED)).update(state=Barter.BARTER_STATE_CANCELLED)
    
    def delete_post(self, reason=None):
        Barter = apps.get_model('barter', 'Barter')
        self.status = self.POST_STATUS_DELETED
        self.deletion_reason = reason
        self.save()
        Barter.objects.filter(Q(requesting_post=self) | Q(requested_post=self)).exclude(state=Barter.BARTER_STATE_CANCELLED).update(state=Barter.BARTER_STATE_CANCELLED)
    
    def free_post(self):
        self.status = 'available'
        self.save()
    
    def change_package(self, new_package):
        """
        Cambia el paquete asociado a la publicación y guarda la transacción en la tabla de PackagePurchase.
        """
        # Guardar la fecha de inicio del nuevo paquete
        self.package_start_date = timezone.now()
        # Registrar la transacción de compra
        create_package_purchase(self, new_package)
        # Actualizar el paquete
        self.package = new_package
        self.save() 
        # Enviar correo electrónico al propietario de la publicación
        self.send_package_change_email(new_package)
        
    def send_package_change_email(self, new_package):
        subject = 'Cambio de paquete en tu publicación'
        plain_message = render_to_string('emails/package_change.txt', {
            'post': self,
            'package': new_package,
            'user': self.author,
        })
        html_message = render_to_string('emails/package_change.html', {
            'post': self,
            'package': new_package,
            'user': self.author,
        })
        send_mail(
            subject,
            plain_message,
            settings.DEFAULT_FROM_EMAIL,  # Remitente
            [self.author.email],   # Destinatario
            html_message=html_message,
            fail_silently=False,
        )

class Question(models.Model): 
    post = models.ForeignKey(Post, related_name='questions', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(validators=[MaxLengthValidator(150)])
    created_at = models.DateTimeField(auto_now_add=True)
    #Como va a ser siempre el dueño de la publicación el que responda la pregunta no necesito hacer una clase nueva
    answer = models.TextField(validators=[MaxLengthValidator(150)],blank=True, null=True)
    
    def __str__(self):
        return f'Question by {self.user.username} on {self.post.title}'

class PackagePurchase(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,verbose_name="Publicación")
    package = models.ForeignKey(Package, on_delete=models.CASCADE,verbose_name="Paquete")
    purchase_date = models.DateTimeField(auto_now_add=True,verbose_name="Fecha")
    price = models.DecimalField(max_digits=6, decimal_places=2,verbose_name="Precio")

    def __str__(self):
        return f"{self.post.title} - {self.package.name} - {self.price}"

#Para cuando podamos cargar mas imagenes
class ImagePost(models.Model):#
    image = models.ImageField(upload_to='post_images')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images', max_length=4)#related_name es el nombre que tiene la otra entidad para llamarla
    #Falta la limitacion de 1 a 4 imágenes
    
    def __str__(self):
        return f"Imagen de {self.post.title}"

barter/forms.py
from django import forms
from .models import Barter
from posts.models import Post

class BarterForm(forms.ModelForm):
    class Meta:
        model = Barter
        fields = ['requesting_post']
        labels = {'requesting_post': 'Postular publicación'}

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        requested_post = kwargs.pop('requested_post')
        super().__init__(*args, **kwargs)
        self.fields['requesting_post'].queryset = Post.objects.filter(
            author=user,
            category=requested_post.category
        ).exclude(
            id__in=Barter.objects.filter(
                requested_post=requested_post
            ).values_list('requesting_post_id', flat=True)
        ).exclude(
            id__in=Barter.objects.filter(
                requesting_post=requested_post
            ).values_list('requested_post_id', flat=True)
        ).exclude(
            status='deleted'
        )

barter/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import CreateView, ListView, DeleteView, TemplateView
from django.urls import reverse_lazy
from accounts.mixins import ClientRequiredMixin, EmployeeRequiredMixin
from .models import Barter, Post
from .forms import BarterForm
from django.db.models import Q
from accounts.models import EmployeeUser

class BarterCreateSuccessView(ClientRequiredMixin,TemplateView):
    template_name = 'temp_messages/barter_requested_successfuly.html'

class BarterCreateView(ClientRequiredMixin, CreateView):
    model = Barter
    form_class = BarterForm
    template_name = 'barter/barter_request.html'
    success_url = reverse_lazy('barter_success')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        requested_post = Post.objects.get(id=self.kwargs['post_id'])
        kwargs['user'] = self.request.user
        kwargs['requested_post'] = requested_post
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.requested_post_id = self.kwargs['post_id']
        return super().form_valid(form)

class BarterListView(ClientRequiredMixin, ListView):
    model = Barter
    template_name = 'barter/my_barters.html'
    context_object_name = 'barters'

    def get_queryset(self):
        user = self.request.user
        return Barter.objects.filter(
            Q(requesting_post__author=user) | Q(requested_post__author=user)
        ).distinct()
    
    def post(self, request, *args, **kwargs):
        selected_barter_id = request.POST.get('selected_barter_id')
        if selected_barter_id:
            return redirect('propose_turns', barter_id=selected_barter_id)
        return super().post(request, *args, **kwargs)
    
class BarterCancelView(ClientRequiredMixin, DeleteView):
    model = Barter
    template_name = 'barter_cancel.html'
    success_url = reverse_lazy('my_barters')
    
    def delete(self, request, *args, **kwargs):
        self.get_object().delete()
        return super().delete(request, *args, **kwargs)
    
class CommittedBartersListView(EmployeeRequiredMixin, ListView):
    model = Barter
    template_name = 'barter/barters_record.html'
    
    def get_queryset(self):
        employee = EmployeeUser.objects.get(id=self.kwargs['employee_id'])
        return Barter.objects.filter(
            Q(branch=employee.branch) & (Q(state='committed') | Q(state='cancelled'))
        )

class BarterFinishedView(EmployeeRequiredMixin,TemplateView):
    template_name = 'temp_messages/barter_finished.html'

templates/barter/barter_request.html
{% extends "_base_wildcard_bootstrap.html" %}

{% block content %}
    <div class="d-flex flex-column align-items-center justify-content-center gap-4">
        <h2>Solicitar Trueque</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div style="text-align: center;">
            <p><button class="btn btn-success"type="submit">Solicitar Trueque</button></p>
            </div>
        </form>
        <p><a href="{% url 'post_new' %}">
            <button class="btn btn-primary">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard-plus" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 7a.5.5 0 0 1 .5.5V9H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V10H6a.5.5 0 0 1 0-1h1.5V7.5A.5.5 0 0 1 8 7"/>
                    <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1z"/>
                    <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0z"/>
                </svg>
                Publicar producto
            </button></a></p>
        <p>
            <a href="{% url 'post_list' %}" class="btn btn-light">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"/>
                </svg>
                Volver
            </a>
        </p>
    </div>
{% endblock %}

templates/barter/barters_record.html
{% extends "_base_wildcard_bootstrap.html" %}
    {% load static %}
    
    {% block title %}Registro de Trueques{% endblock title %}
    
    {% block custom_styles %}
        <link rel="stylesheet" href="{% static 'styles/barters/barters_list.css' %}">
    {% endblock custom_styles %}
    
    {% block content %}
    <div class="barter-list-container">
        <h1>Registro de Trueques</h1>
        {% for barter in object_list %}
        <div class="barter-item">
            <div class="barter-header">
                <h2>{{ barter }}</h2>  
            </div>
            {% if barter.state == 'cancelled' %}
            <p>
                <button type="button" class="btn btn-light" data-toggle="modal" data-target="#reportModal{{ barter.id }}">Ver reporte</button>
            </p>
            {% else %}
            <p>
                <button type="button" class="btn btn-light" data-toggle="modal" data-target="#profitModal{{ barter.id }}">Ver reporte</button>
            </p>
            {% endif %}
            <p class="barter-state {% if barter.state == 'requested' %}requested-state{% elif barter.state == 'accepted' %}accepted-state{% elif barter.state == 'parcial_accepted' %}parcial_accepted-state{% elif barter.state == 'committed' %}committed-state{% elif barter.state == 'cancelled' %}cancelled-state{% endif %}">{{ barter.get_state_display }}</p>
        </div>
    
        <!-- Modal para reporte de cancelación -->
        <div class="modal fade" id="reportModal{{ barter.id }}" tabindex="-1" role="dialog" aria-labelledby="reportModalLabel{{ barter.id }}" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="reportModalLabel{{ barter.id }}">Reporte de Cancelación</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {% with report=barter.get_cancellation_report %}
                                <p><strong>Empleado:</strong> {{ barter.employee }}</p>
                                <p><strong>Motivo:</strong> {{ report.reason }}</p>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
         <!-- Modal para ganancia de trueque cometido -->
        <div class="modal fade" id="profitModal{{ barter.id }}" tabindex="-1" role="dialog" aria-labelledby="profitModalLabel{{ barter.id }}" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="profitModalLabel{{ barter.id }}">Ganancia del Trueque</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p><strong>Empleado:</strong> {{ barter.employee }}</p>
                        <p><strong>Ganancia:</strong> ${{ barter.income }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        <p><a href="{% url 'home' %}" class="btn btn-light">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"/>
              </svg>
                Volver
        </a></p>
    </div>
    {% endblock content %}

templates/barter/employee_cancel_barter.html
{% extends "_base_wildcard_bootstrap.html" %}
{% load static %}

{% block title %}Cancelar Trueque{% endblock title %}
{% block content %}
<div class="cancellation-form-container">
    <h1>Cancelar Trueque</h1>
    <form method="post">
        {% csrf_token %}
        <h5>Motivo de la cancelación:</h5>
        {{ form.as_p }}
        <p><button class="btn btn-danger" type="submit">Registrar Cancelación</button></p>
    </form>
    <p><a href="{% url 'employee_appointments_list' employee.id %}" class="btn btn-light">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"/>
          </svg>
            Volver
    </a></p>
</div>
{% endblock %}
{% block extra_css %}
<style>
    .wider-textarea {
        width: 100%; /* Ajusta el ancho según sea necesario */
    }
</style>
{% endblock %}

templates/barter/my_barters.html
{% extends "_base_wildcard_bootstrap.html" %}
{% load static %}

{% block title %}Mis Trueques{% endblock title %}

{% block custom_styles %}
    <link rel="stylesheet" href="{% static 'styles/barters/barters_list.css' %}">
{% endblock custom_styles %}

{% block content %}
<div class="barter-list-container">
    <h1>Mis Trueques</h1>
    {% for barter in object_list %}
    <div class="barter-item">
        <div class="barter-header">
            <h2>
                <a href="{% url 'post_detail' barter.requesting_post.pk %}">{{ barter.requesting_post.title }}</a> 
                x 
                <a href="{% url 'post_detail' barter.requested_post.pk %}">{{ barter.requested_post.title }}</a>
            </h2>  
            <p class="barter-state {% if barter.state == 'requested' %}requested-state{% elif barter.state == 'accepted' %}accepted-state{% elif barter.state == 'parcial_accepted' %}parcial_accepted-state{% elif barter.state == 'committed' %}committed-state{% elif barter.state == 'cancelled' %}cancelled-state{% endif %}">{{ barter.get_state_display }}</p>
            {% if barter.state == 'accepted' %}
            <p><a href="{% url 'appointments_list' %}" class="btn btn-light">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-check" viewBox="0 0 16 16">
                    <path d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0"/>
                    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5M1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4z"/>
                </svg>
                Mis turnos
            </a>
            {% endif %}
            {% if barter.state == 'requested' or barter.state == 'parcial_accepted' %}
                {% if barter.requested_post.author == request.user %}
                    {% if barter.state == 'requested' %}
                        <form method="post" action="{% url 'propose_turns' barter.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="barter_id" value="{{ barter.id }}">
                            <button type="submit" class="btn btn-success">Aceptar Trueque</button>
                        </form>
                    {% else %}
                        <a href="{% url 'turns_list' barter.id%}?barter_id={{ barter.id }}" class="btn btn-info">Proponer Turnos</a>
                    {% endif %}
                {% elif barter.state == 'parcial_accepted' %}
                    <a href="{% url 'turns_list' barter.id%}?barter_id={{ barter.id }}" class="btn btn-info">Ver Propuestas de Turnos</a>
                {% endif %}
                <form method="post" action="{% url 'barter_cancel' barter.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Cancelar</button>
                </form>
            {% endif %}
        
        </div>
    </div>
    {% endfor %}
    <p><a href="{% url 'home' %}" class="btn btn-light">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"/>
          </svg>
            Volver
    </a></p>
</div>
{% endblock content %}