adminpanel/urls.py
from django.urls import path
from .views import (
    BranchListView,
    BranchCreateView,
    BranchUpdateView,
    BranchDeleteView,
    AdminPanelView,
    EmployeeSignupView,
    EmployeeSuccessView,
    update_company_email,
    update_company_email_success
    
)

urlpatterns = [
    path("", AdminPanelView.as_view(), name="adminpanel"),
    path("branches/", BranchListView.as_view(), name="show_branches"),
    path("branches/add/", BranchCreateView.as_view(), name="register_new_branch"),
    path("branches/edit/<int:pk>/", BranchUpdateView.as_view(), name="edit_branch"),
    path("branches/delete/<int:pk>/", BranchDeleteView.as_view(), name="delete_branch"),
    path("employee_signup/", EmployeeSignupView.as_view(), name="employee_signup"),
    path(
        "success/<int:employee_id>/",
        EmployeeSuccessView.as_view(),
        name="employee_success",
    ),
    path('update-company-email/', update_company_email, name='update_company_email'),
    path('update-company-email/success/', update_company_email_success, name='update_company_email_success')
]

ferreplus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    path("accounts/", include("accounts.urls")),
    # Local apps
    path("", include("pages.urls")),
    path("posts/", include("posts.urls")),
    path("adminpanel/", include("adminpanel.urls")),
    path("barter/", include("barter.urls")),
    path("turns/", include("turns.urls")),
    path("employee/", include("employeepanel.urls")),
    path("payments/", include("payments.urls")),
    path("metrics_analysis/", include("metrics_analysis.urls")),
    path("catalog/", include("catalogo.urls"))
]

if settings.DEBUG: #Solo proyecto en desarrollo, falta para producción
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    HomePageView,
    ClientHomeView,
    AdmiHomeView,
    EmployeeHomeView,
    GoBack,
    PasswordChangeSuccessView,
    EmailEditSuccessView,
    ShowContactInfo,
    show_contact_info
)


urlpatterns = [
    path("home", HomePageView.as_view(), name="home"),
    path("adminpanel/", AdmiHomeView.as_view(), name="admi_home"),
    path("employee/", EmployeeHomeView.as_view(), name="employee_home"),
    path(
        "password/change/successful",
        PasswordChangeSuccessView.as_view(),
        name="password_change_success",
    ),
    path(
        "profile-edit-success",
        EmailEditSuccessView.as_view(),
        name="profile_edit_success",
    ),
    path("", ClientHomeView.as_view(), name="client_home"),
    path("", GoBack.as_view(), name="go_back"),
    path("contact/", show_contact_info, name="contact"),
]

adminpanel/models.py
from django.db import models


class Contact(models.Model):
    email = models.EmailField(max_length=254, default="ferreplus@gmail.com")

    def __str__(self):
        return self.email

posts/models.py
from django.db import models
from django.utils import timezone
from django.apps import apps
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.core.validators import MaxLengthValidator
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.conf import settings
from branches.models import Branch

User = get_user_model()

class Package(models.Model):
    PACKAGE_NONE = 'none'
    PACKAGE_BRONCE = 'bronce'
    PACKAGE_PLATA = 'plata'
    PACKAGE_ORO = 'oro'
    
    PACKAGE_CHOICES = [
        (PACKAGE_NONE, 'Ninguno'),
        (PACKAGE_BRONCE, 'Bronce'),
        (PACKAGE_PLATA, 'Plata'),
        (PACKAGE_ORO, 'Oro'),
    ]
    name = models.CharField(max_length=10, choices=PACKAGE_CHOICES, unique=True,default=PACKAGE_NONE)
    price = models.DecimalField(max_digits=6, decimal_places=2)  # Precio del paquete
    priority = models.IntegerField(default=5) #Para ordenamiento de publicaciones

    def __str__(self):
        return self.get_name_display()

def create_package_purchase(post, package):
        PackagePurchase.objects.create(
            post=post,
            package=package,
            price=package.price
    )

class Post(models.Model):
    POST_STATUS_AVAILABLE = 'available'
    POST_STATUS_RESERVED = 'reserved'
    POST_STATUS_COMPLETED = 'completed'
    POST_STATUS_PAUSED = "paused"
    POST_STATUS_DELETED = "deleted"
    POST_STATUS_CHOICES = (
        (POST_STATUS_AVAILABLE, 'Disponible'),
        (POST_STATUS_RESERVED, 'Reservado'),
        (POST_STATUS_COMPLETED, 'Finalizado'),
        (POST_STATUS_PAUSED, "Pausado"),
        (POST_STATUS_DELETED, "Eliminado")
    )

    HERRAMIENTAS = "tools" #En la BD su campo se denomina con el String 
    CONSTRUCCION = "construction"
    FERRETERIA_GRAL = "general_hardware_store"
    ELECTRICIDAD = "electrical"
    FONTANERIA = "plumbing"
    JARDIN = "gardens"
    CHOICES = [
        (HERRAMIENTAS, 'Herramientas'),
        (CONSTRUCCION, 'Construcción'),
        (FERRETERIA_GRAL, 'Ferretería general'),
        (ELECTRICIDAD, "Electricidad"),
        (FONTANERIA, 'Fontanería'),
        (JARDIN, 'Jardin'),
    ]
    
    title = models.CharField(max_length=50,verbose_name="Titulo")
    author = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name="Autor") 
    body = models.TextField(blank=True, null=True) 
    image = models.ImageField(upload_to="post_images") #Para una imagen sola
    category = models.CharField(max_length=22, choices=CHOICES,verbose_name="Categoría")
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL,null=True,verbose_name="Sucursal") #Sucursal
    original_branch_id = models.IntegerField(null=True) #ID sucursal original para cuando eliminamos una sucursal y la publi se ponga en pausado
    new = models.BooleanField(blank=True, null=True,)
    brand = models.CharField(max_length=30,blank=True, null=True,verbose_name="Marca") #marca
    status = models.CharField(max_length=20, choices=POST_STATUS_CHOICES, default=POST_STATUS_AVAILABLE,) 
    package = models.ForeignKey(Package, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Paquete")
    package_start_date = models.DateTimeField(null=True, blank=True)  # Fecha de inicio del paquete
    deletion_reason = models.TextField(null=True, blank=True, verbose_name="Razón de eliminación")
    
    def has_unanswered_questions(self):
        return self.questions.filter(Q(answer__isnull=True) | Q(answer='')).exists()
    
    def __str__(self):
        return self.title
    
    def complete_post(self):
        self.status = 'completed'
        self.save()

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"pk": self.pk})
    
    def reserve_post(self):
        Barter = apps.get_model('barter', 'Barter')
        
        self.status='reserved'
        self.save()
        
        # Cancelar todos los trueques donde esta publicación está involucrada y no están ya cancelados
        self.requesting_barters.filter(~Q(state=Barter.BARTER_STATE_CANCELLED)).update(state=Barter.BARTER_STATE_CANCELLED)
        self.requested_barters.filter(~Q(state=Barter.BARTER_STATE_CANCELLED)).update(state=Barter.BARTER_STATE_CANCELLED)
    
    def delete_post(self, reason=None):
        Barter = apps.get_model('barter', 'Barter')
        self.status = self.POST_STATUS_DELETED
        self.deletion_reason = reason
        self.save()
        Barter.objects.filter(Q(requesting_post=self) | Q(requested_post=self)).exclude(state=Barter.BARTER_STATE_CANCELLED).update(state=Barter.BARTER_STATE_CANCELLED)
    
    def free_post(self):
        self.status = 'available'
        self.save()
    
    def change_package(self, new_package):
        """
        Cambia el paquete asociado a la publicación y guarda la transacción en la tabla de PackagePurchase.
        """
        # Guardar la fecha de inicio del nuevo paquete
        self.package_start_date = timezone.now()
        # Registrar la transacción de compra
        create_package_purchase(self, new_package)
        # Actualizar el paquete
        self.package = new_package
        self.save() 
        # Enviar correo electrónico al propietario de la publicación
        self.send_package_change_email(new_package)
        
    def send_package_change_email(self, new_package):
        subject = 'Cambio de paquete en tu publicación'
        plain_message = render_to_string('emails/package_change.txt', {
            'post': self,
            'package': new_package,
            'user': self.author,
        })
        html_message = render_to_string('emails/package_change.html', {
            'post': self,
            'package': new_package,
            'user': self.author,
        })
        send_mail(
            subject,
            plain_message,
            settings.DEFAULT_FROM_EMAIL,  # Remitente
            [self.author.email],   # Destinatario
            html_message=html_message,
            fail_silently=False,
        )

class Question(models.Model): 
    post = models.ForeignKey(Post, related_name='questions', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(validators=[MaxLengthValidator(150)])
    created_at = models.DateTimeField(auto_now_add=True)
    #Como va a ser siempre el dueño de la publicación el que responda la pregunta no necesito hacer una clase nueva
    answer = models.TextField(validators=[MaxLengthValidator(150)],blank=True, null=True)
    
    def __str__(self):
        return f'Question by {self.user.username} on {self.post.title}'

class PackagePurchase(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,verbose_name="Publicación")
    package = models.ForeignKey(Package, on_delete=models.CASCADE,verbose_name="Paquete")
    purchase_date = models.DateTimeField(auto_now_add=True,verbose_name="Fecha")
    price = models.DecimalField(max_digits=6, decimal_places=2,verbose_name="Precio")

    def __str__(self):
        return f"{self.post.title} - {self.package.name} - {self.price}"

#Para cuando podamos cargar mas imagenes
class ImagePost(models.Model):#
    image = models.ImageField(upload_to='post_images')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images', max_length=4)#related_name es el nombre que tiene la otra entidad para llamarla
    #Falta la limitacion de 1 a 4 imágenes
    
    def __str__(self):
        return f"Imagen de {self.post.title}"

adminpanel/forms.py
from django import forms
from branches.models import Branch
from .models import Contact

class BranchForm(forms.ModelForm):

    class Meta:
        model = Branch
        fields = ["city", "address", "postal_code", "phone"]
        labels = {
            "city": "Ciudad",
            "address": "Dirección",
            "postal_code": "Código Postal",
            "phone": "Teléfono"
        }

    def __init__(self, *args, **kwargs):
        super(BranchForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.required = True

    def clean(self):
        cleaned_data = super().clean()
        city = cleaned_data.get("city")
        address = cleaned_data.get("address")
        postal_code = cleaned_data.get("postal_code")
        if Branch.objects.filter(city=city, address=address, postal_code=postal_code).exists():
            raise forms.ValidationError("Ya existe una sucursal en esa ubicación.")

        return cleaned_data


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ["email"]

adminpanel/views.py
from django.db.models.query import QuerySet
from django.views.generic import ListView, CreateView, TemplateView
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy
from branches.models import Branch
from .forms import BranchForm, ContactForm
from accounts.mixins import AdminRequiredMixin
from django.views import View
from accounts.forms import EmployeeUserCreationForm
from accounts.models import EmployeeUser
from django.shortcuts import render, redirect
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from .models import Contact


class AdminPanelView(AdminRequiredMixin, TemplateView):
    template_name = 'adminpanel.html'

class BranchListView(AdminRequiredMixin, ListView):
    model = Branch
    template_name = 'show_branches.html'
    context_object_name = 'branches'

    def get_queryset(self):
        return Branch.active_objects.all()

class BranchCreateView(AdminRequiredMixin, CreateView):
    model = Branch
    form_class = BranchForm
    template_name = 'register_new_branch.html'
    success_url = reverse_lazy('show_branches')

class BranchUpdateView(AdminRequiredMixin, UpdateView):
    model = Branch
    form_class = BranchForm
    template_name = 'edit_branch.html'
    success_url = reverse_lazy('show_branches')

    def get_form_class(self):
            return RestrictedBranchForm 

class RestrictedBranchForm(AdminRequiredMixin, BranchForm):
    class Meta(BranchForm.Meta):
        exclude = ['city', 'postal_code'] 

class BranchDeleteView(AdminRequiredMixin, DeleteView):
    model = Branch
    template_name = 'confirm_branch_removal.html'
    success_url = reverse_lazy('show_branches')

    def delete(self, request, *args, **kwargs):
        self.get_object().delete()
        return super().delete(request, *args, **kwargs)


class EmployeeSignupView(AdminRequiredMixin, View):
    def get(self, request):
        form = EmployeeUserCreationForm()
        return render(request, "account/employee_signup.html", {"form": form})

    def post(self, request):
        form = EmployeeUserCreationForm(request.POST)
        if form.is_valid():
            employee = form.save()
            messages.success(
                request,
                f"Empleado {employee.nombre} {employee.apellido} registrado exitosamente.",
            )
            return redirect("employee_success", employee_id=employee.id)
        return render(request, "account/employee_signup.html", {"form": form})


class EmployeeSuccessView(AdminRequiredMixin, View):
    def get(self, request, employee_id):
        employee = get_object_or_404(EmployeeUser, id=employee_id)
        return render(request, "account/employee_success.html", {"employee": employee})


def update_company_email(request):
    company_email, created = Contact.objects.get_or_create(
        pk=0
    )  # Ensure only one instance exists
    if request.method == "POST":
        form = ContactForm(request.POST, instance=company_email)
        if form.is_valid():
            form.save()
            return redirect(
                "update_company_email_success"
            )  # Redirect to a success page
    else:
        form = ContactForm(instance=company_email)

    return render(request, "update_company_email.html", {"form": form})


def update_company_email_success(request):
    return render(request, "update_company_email_success.html")

templates/adminpanel.html
{% extends "_base_wildcard_bootstrap.html" %} 
{% load static %}

{% block title %}Ferreplus{% endblock title %} 
<head>
    {% block custom_styles %}
        <link rel="stylesheet" href="{% static 'styles/home/adminpanel.css' %}">
    {% endblock custom_styles %}
</head>
{% block content %}
    <div>
        <div class="home-container">
            <div class="admin-dashboard">
                <div>
                    <h1>Panel de Administrador</h1>
                    <h1>Hola <strong>{{ request.user.username }}</strong>!</h1>
                    <h2>Qué bueno verte de nuevo</h2>
                </div>
                <div class="admin_menu">
                    <p><a href="{% url 'show_branches' %}">
                        <button class="menu-button">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-shop" viewBox="0 0 16 16">
                                <path d="M2.97 1.35A1 1 0 0 1 3.73 1h8.54a1 1 0 0 1 .76.35l2.609 3.044A1.5 1.5 0 0 1 16 5.37v.255a2.375 2.375 0 0 1-4.25 1.458A2.37 2.37 0 0 1 9.875 8 2.37 2.37 0 0 1 8 7.083 2.37 2.37 0 0 1 6.125 8a2.37 2.37 0 0 1-1.875-.917A2.375 2.375 0 0 1 0 5.625V5.37a1.5 1.5 0 0 1 .361-.976zm1.78 4.275a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 1 0 2.75 0V5.37a.5.5 0 0 0-.12-.325L12.27 2H3.73L1.12 5.045A.5.5 0 0 0 1 5.37v.255a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0M1.5 8.5A.5.5 0 0 1 2 9v6h1v-5a1 1 0 0 1 1-1h3a1 1 0 0 1 1 1v5h6V9a.5.5 0 0 1 1 0v6h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1V9a.5.5 0 0 1 .5-.5M4 15h3v-5H4zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1zm3 0h-2v3h2z"/>
                              </svg>
                            Ver sucursales
                        </button>
                    </a></p>
                    <p><a href="{% url 'employee_signup' %}">
                        <button class="menu-button">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-add" viewBox="0 0 16 16">
                                <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0m-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0M8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4"/>
                                <path d="M8.256 14a4.5 4.5 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10q.39 0 .74.025c.226-.341.496-.65.804-.918Q8.844 9.002 8 9c-5 0-6 3-6 4s1 1 1 1z"/>
                              </svg>
                            Registrar Empleado
                        </button>
                    </a></p>
                    <p><a href="{% url 'package_list' %}">
                        <button class="menu-button">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-seam" viewBox="0 0 16 16">
                                <path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5l2.404.961L10.404 2zm3.564 1.426L5.596 5 8 5.961 14.154 3.5zm3.25 1.7-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464z"/>
                            </svg>
                            Administrar paquetes
                        </button>
                    </a></p>
                    <p>
                        <a href="{% url 'metrics' %}" style="color: black">
                            <button class="menu-button">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard2-data" viewBox="0 0 16 16">
                                  <path d="M9.5 0a.5.5 0 0 1 .5.5.5.5 0 0 0 .5.5.5.5 0 0 1 .5.5V2a.5.5 0 0 1-.5.5h-5A.5.5 0 0 1 5 2v-.5a.5.5 0 0 1 .5-.5.5.5 0 0 0 .5-.5.5.5 0 0 1 .5-.5z"/>
                                  <path d="M3 2.5a.5.5 0 0 1 .5-.5H4a.5.5 0 0 0 0-1h-.5A1.5 1.5 0 0 0 2 2.5v12A1.5 1.5 0 0 0 3.5 16h9a1.5 1.5 0 0 0 1.5-1.5v-12A1.5 1.5 0 0 0 12.5 1H12a.5.5 0 0 0 0 1h.5a.5.5 0 0 1 .5.5v12a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5z"/>
                                  <path d="M10 7a1 1 0 1 1 2 0v5a1 1 0 1 1-2 0zm-6 4a1 1 0 1 1 2 0v1a1 1 0 1 1-2 0zm4-3a1 1 0 0 0-1 1v3a1 1 0 1 0 2 0V9a1 1 0 0 0-1-1"/>
                                </svg>
                                Ver Reportes
                            </button>
                        </a>
                    </p>
                    <p>
                        <a href="{% url 'product_create' %}" style="color: black; text-decoration: none;">
                            <button class="menu-button">
                                <img src="{% static 'img/icons/add_product.png' %}" style="width: 16px;" />
                                Agregar nuevo producto
                            </button>
                        </a>
                    </p>
                    <p><a href="{% url 'update_company_email' %}" style="color: black">
                        <button class="menu-button" style="margin-top: 15px">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-at" viewBox="0 0 16 16">
                              <path d="M2 2a2 2 0 0 0-2 2v8.01A2 2 0 0 0 2 14h5.5a.5.5 0 0 0 0-1H2a1 1 0 0 1-.966-.741l5.64-3.471L8 9.583l7-4.2V8.5a.5.5 0 0 0 1 0V4a2 2 0 0 0-2-2zm3.708 6.208L1 11.105V5.383zM1 4.217V4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v.217l-7 4.2z"/>
                              <path d="M14.247 14.269c1.01 0 1.587-.857 1.587-2.025v-.21C15.834 10.43 14.64 9 12.52 9h-.035C10.42 9 9 10.36 9 12.432v.214C9 14.82 10.438 16 12.358 16h.044c.594 0 1.018-.074 1.237-.175v-.73c-.245.11-.673.18-1.18.18h-.044c-1.334 0-2.571-.788-2.571-2.655v-.157c0-1.657 1.058-2.724 2.64-2.724h.04c1.535 0 2.484 1.05 2.484 2.326v.118c0 .975-.324 1.39-.639 1.39-.232 0-.41-.148-.41-.42v-2.19h-.906v.569h-.03c-.084-.298-.368-.63-.954-.63-.778 0-1.259.555-1.259 1.4v.528c0 .892.49 1.434 1.26 1.434.471 0 .896-.227 1.014-.643h.043c.118.42.617.648 1.12.648m-2.453-1.588v-.227c0-.546.227-.791.573-.791.297 0 .572.192.572.708v.367c0 .573-.253.744-.564.744-.354 0-.581-.215-.581-.8Z"/>
                            </svg>
                            Modificar información de contacto
                    </a></p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/contact_info.html
{% extends "_base_wildcard_bootstrap.html" %}
{% load static %}

{% block title %}Ferreplus{% endblock title %} 

{% block custom_styles %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/contact_info/contact_info.css' %}">
    <link rel="stylesheet" href="{% static 'styles/home/client_home.css' %}">
{% endblock custom_styles %}
{% block content %}
    <div class="accordion" id="accordionBranches" style="width:50%;">
        <h3 class="title">Informacion de Nuestras Sucursales: </h3>
        {% if not branches_by_city %}
        <p style="color:red; font-weight:bold">En este momento no tenemos sucursales activas</p>
        <p>Puede comunicarse con nosotros a través de nuestro correo:</p>
        {% endif %}
        {% for city, branches in branches_by_city.items %}
            <div class="accordion-item">
                <h2 class="accordion-header" id="heading{{ forloop.counter }}">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="false" aria-controls="collapse{{ forloop.counter }}">
                        {{city}}
                    </button>
                </h2>
                <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse {% if forloop.first %}show{% endif %}" data-bs-parent="#accordionBranches">
                    <div class="accordion-body d-flex flex-wrap">
                        {% for branch in branches %}
                            <div class="card" style="width: 18rem;">
                                <div class="card-body">
                                  <h5 class="card-title">Sucursal {{forloop.counter}}</h5>
                                  <p class="card-text">Calle: {{branch.address}}</p>
                                  <p class="card-text">Tel.: {{branch.phone}}</p>
                                  <p class="card-text">C.P: {{branch.postal_code}}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
        <p>{{company_email}}</p>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{% endblock content %}

templates/home.html
{% extends "_base_wildcard_bootstrap.html" %} 
{% load static %}
{% load home %}

{% block title %}Ferreplus{% endblock title %} 
<head>
    {% block custom_styles %}
        <link rel="stylesheet" href="{% static 'styles/home/home.css' %}">
    {% endblock custom_styles %}
</head>
{% block content %}
    <div class="d-flex flex-column" style="min-width: 100vw; min-height: 100vh; margin: none;">
        <div>
            {% show_home_banner %}
        </div>
        <div class="d-flex flex-column" style="min-width: 100vw;"">
            {% show_home_site_features %}
        </div>
    </div>
{% endblock content %}

templates/post_detail.html
<!-- templates/post_detail.html -->
{% extends "_base.html" %}
{% load static %} {#Si es que va#}

{% block content %}
<div class="post-entry">
    <h1> aglo</h1>
    <h1> aglo</h1>
    <h2>{{ post.title }}</h2>
    <p>{{ post.body }}</p>
    <p>{{ post.author }}</p>
    <p>{{ post.category }}</p>
    <p>{{ post.new }}</p>
    <p>{{ post.brand }}</p>
    <p>{{ post.status }}</p>
    <p>{{ post.manufacturing_date }}</p>
</div>



<a href="{% url 'post_edit' post.pk %}">+ Editar publicación</a>
<p><a href="{% url 'post_delete' post.pk %}">+ Eliminar publicación</a></p>
<p> <a href="{% url 'post_list' %}">Todas las publicaciones</a>.</p>
{% endblock content %}

templates/post_new.html
<!-- templates/post_new.html -->
{% extends "_base.html" %}

{% block content %}
<h1>New post</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar">
</form>
{% endblock content %}